# Generated by Django 3.2.4 on 2021-06-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('abstract', models.TextField(null=True)),
                ('abstract_formatted', models.TextField(null=True)),
                ('fulltext', models.TextField(null=True)),
                ('doi', models.TextField(null=True)),
                ('eid', models.TextField(null=True)),
                ('link', models.TextField(null=True)),
                ('publisher', models.TextField(null=True)),
                ('publish_date', models.TextField(null=True)),
                ('keywords', models.TextField(null=True)),
            ],
        ),
    ]
